name: Deploy Lambda Function

on:
  push:
    branches: [master]
jobs:
  build:

    runs-on: ubuntu-latest
    env:
      ECR_IMAGE_TAG: latest
      AWS_DEFAULT_REGION: us-east-1
      AWS_LAMBDA_FUNC_NAME: SarjAnalytics
      AWS_ECR_REPOSITORY_NAME: aws-lambda-ecr

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_DEFAULT_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        docker build \
            -t $ECR_REGISTRY/${{ env.AWS_ECR_REPOSITORY_NAME }}:${{ env.ECR_IMAGE_TAG }} .
        docker push $ECR_REGISTRY/${{ env.AWS_ECR_REPOSITORY_NAME }}:${{ env.ECR_IMAGE_TAG }}
        echo "::set-output name=image::$ECR_REGISTRY/${{ env.AWS_ECR_REPOSITORY_NAME }}:${{ env.ECR_IMAGE_TAG }}"
    
    - name: Deploy to AWS Lambda
      run: |
        aws lambda update-function-code \
        --function-name ${{ env.AWS_LAMBDA_FUNC_NAME }} \
        --image-uri "$ECR_REGISTRY/${{ env.AWS_ECR_REPOSITORY_NAME }}:${{ env.ECR_IMAGE_TAG }}"
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ env.AWS_DEFAULT_REGION }}